aerogear/aerogear-app-metrics

Gopkg.lock, Gopkg.toml, pkg/web/interfaces.go, pkg/web/metricsHandler.go, pkg/web/metricsHandler_test.go
As HTTP endpoint is already created part of https://github.com/aerogear/aerogear-metrics-api/pull/10, this PR only implements tests for it.
This PR is blocked by https://github.com/aerogear/aerogear-metrics-api/pull/10
As we don't have the DB integration working yet, we cannot do E2E tests.
Thus, we decided to write some unit tests for the endpoint only. 
Tests for the endpoint handler shouldn't call `MetricsService` for real as it is not functioning properly. So, we created a "mock" for that service and passed it to the endpoint handler.
The value gained from the unit test is actually very little. It just checks if the mocked service is called with right parameters in the happy case. In the bad cases (invalid JSON or empty request body), the test verifies that nothing sent to the service …
=> AEROGEAR-2044 - HTTP Endpoint

.circleci/config.yml, .gitignore, Gopkg.lock, Gopkg.toml, cmd/metrics-api/metrics-api.go, deployments/docker/docker-compose.yml, makefile, pkg/config/config.go, pkg/config/config_test.go, pkg/dao/dao.go, pkg/dao/dao_test.go, pkg/dao/db.go, pkg/dao/db_test.go, pkg/mobile/interfaces.go, pkg/mobile/metrics.go, pkg/mobile/metrics_test.go, pkg/mobile/types.go, pkg/web/healthzHandler.go, pkg/web/healthzHandler_test.go, pkg/web/interfaces.go, pkg/web/metricsHandler.go, pkg/web/metricsHandler_test.go, pkg/web/router.go
This PR ended up turning into a mega PR but this is the initial implementation that allows us to store mobile metrics in the database. There are a number of things to be aware of:
* There is a small amount of validation. The incoming data is parsed into a struct which filters out unnecessary fields. additionally, there are some small checks at the DB layer. ClientId cannot be an empty string and by data field will not accept invalid json. There is no other validation (right now).
* Right now, the client timestamp is being parsed but not being saved. The `event_time` field is populated by Postgres at the time of insert.
* The db_test.go and dao_test.go are actually integration tests. However by default they will not run because of the `// +build integration` build tag added at the top of …
=> Database Integration

pkg/mobile/metrics_test.go, pkg/mobile/types.go, pkg/mobile/types_test.go, pkg/web/metricsHandler.go, pkg/web/metricsHandler_test.go
This PR adds a function `Validate() (valid bool, reason string)` to the Metric struct and uses that function in the metrics handler to check for some basic validation cases. clientId not existing and Data not existing or being empty object.
This prevents us from saving empty entries in postgres. Unit tests have been added for the Validate() function.
I've constructed some curl requests and expected responses so you can try out. For now the server returns the same data that is saved in the DB. This is handy in development.
The happy case - full payload. (Excluding client timestamp - will look after this in a separate PR) 
```
curl -X POST \
http://localhost:3000/metrics \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-H 'Postman-Token: …
```
=> feat: add some very basic validation to Metric struct

makefile, pkg/dao/dao_test.go, pkg/dao/db_test.go
The config pkg was refactored to use a map as opposed to a struct. The integration tests were not updated to reflect the change. We never noticed the build failing because the `make test-integration-cover` command is using a `foreach` syntax that wasn't returning a non-zero exit code. The make command has been updated to ensure a failing test will cause `make` to fail properly.
ping @psturc thanks for catching this.
=> fix(tests): ensure integration tests use config pkg properly

.circleci/config.yml, CONTRIBUTING.md, README.md, cmd/metrics-api/metrics-api.go, makefile, pkg/dao/dao_test.go, pkg/dao/db_test.go, pkg/web/interfaces.go, pkg/web/metricsHandler.go, pkg/web/metricsHandler_test.go
This change renames the metrics service to aerogear-app-metrics
=> breaking: rename repo to aerogear-app-metrics

.gitignore, .goreleaser.yml, Dockerfile, README.md, docker-compose.yml, makefile
This PR does two things:
* Changes the default binary name from `metrics` (which is unclear) to `aerogear-app-metrics`
* Drastic improvements to the Readme
Ping @paolobueno @aliok @david-martin
=> fix: rename binary to aerogear-app-metrics & update docs

pkg/mobile/types_test.go
goreportcard.com made me notice this issue. We weren't actually calling `t.Errorf()` in these tests which would mean they would always fail.
=> fix(tests): use t.Errorf() in types_test.go

cmd/metrics-api/metrics-api.go, pkg/config/config.go, pkg/config/config_test.go, pkg/dao/dao_test.go, pkg/dao/db.go, pkg/dao/db_test.go, pkg/mobile/types.go, pkg/mobile/types_test.go
This PR introduces a number of enhancements: 
* Client ID max length is now enforced at the business logic layer using metric.Validate(). This allows us to respond with a proper message when the max length has been exceeded. Ping @psturc.
* the dao package now has some small amount of retry logic which will let the server retry connecting to the db for up to 5 seconds before failing. This solves a minor issue particularly in docker-compose where the server sometimes starts before the database is ready to accept connections. Ping @josemigallas.
* Configuration parsing has been hardened and refactored. All connection options supported by the postgres driver are now supported and the connection string can be dynamically generated based off what config/env vars are present. This means we …
=> fix: enhancements to config parsing and dao

Gopkg.lock, pkg/dao/dao.go, pkg/dao/dao_test.go, pkg/dao/db.go, pkg/mobile/interfaces.go, pkg/mobile/metrics.go, pkg/mobile/metrics_test.go, pkg/mobile/types.go, pkg/mobile/types_test.go, pkg/web/metricsHandler.go, pkg/web/metricsHandler_test.go
Because this PR introduces changes to the database you must delete the old db container cached by docker-compose. Do the following:
* docker ps -a | grep db_1
* `docker rm` the ids of any containers returned back by the previous command
* restart the db using `docker-compose up --force-recreate --build db`
For each case we are going to make a `curl` request and then check the results in the database.
Logging into the database and checking the contents of the `mobileappmetrics` table can be done as follows:
```
psql -U postgresql -d aerogear_mobile_metrics --host localhost
Password for user postgresql: #postgres
aerogear_mobile_metrics=> select * from mobileappmetrics;
```
For each section below, perform the curl request and then check the database for the expected result. We are going to …
=> fix: save client timestamp in database if present

Gopkg.lock, Gopkg.toml, cmd/metrics-api/metrics-api.go, pkg/config/config.go, pkg/config/config_test.go, pkg/dao/db.go, pkg/web/metricsHandler.go, pkg/web/middlewares.go
This introduces logging using the popular library [logrus](https://github.com/sirupsen/logrus). Most of the logging is in the MetricsHandler because this is where all the action happens.
The logs have 6 different log levels as defined by logrus:
* Debug
* Info
* Warning
* Error
* Fatal
* Panic
The logs can be displayed in two different formats, `text` or `json`.
example of a text log:
```
time="2018-03-01T15:20:57Z" level=info msg="Starting application" listenAddress=":3000"
```
example of the same log in json:
```
{"level":"info","listenAddress":":3000","msg":"Starting application","time":"2018-03-01T15:21:32Z"}
```
Log levels and log format can be configured with the following env variables:
* `LOG_LEVEL`
* can be one of [debug, info, warning, error, fatal, panic]
* default is `info`
* …
=> fix: initial logging implementation using logrus

pkg/mobile/types.go, pkg/mobile/types_test.go
The result of this PR is that the server expects a payload as follows:
```
{
"clientId": "9796fb69-a566-43fb-b932-03951d82437f",
"timestamp": 1519989859342,
"data": {
"security": [
{
"type": "org.aerogear.mobile.security.checks.DeveloperModeCheck",
"name": "Developer Mode Check",
"passed": true
},
{
"type": "org.aerogear.mobile.security.checks.EmulatorCheck",
"name": "Emulator Check",
"passed": false
},
{
"type": "org.aerogear.mobile.security.checks.DebuggerCheck",
"name": "Debugger Check",
"passed": false
},
{
"type": "org.aerogear.mobile.security.checks.RootedCheck",
"name": "Rooted Check",
"passed": false
},
{
"type": "org.aerogear.mobile.security.checks.ScreenLockCheck",
"name": "Screen Lock Check",
"passed": false
}
]
}
}
```
There is also some basic validation logic for the security …
=> feat: initial parsing of security metrics

.circleci/config.yml, makefile
This PR adds the GOCACHE=off flag which ensures test results are not cached in between test runs. The reason for this is the integration tests were reporting passing tests even though the database was not running.
Additionally, it adds a `-failfast` option to the integration tests. This ensures the tests fail after the first test case failure. The reason for adding this is because the integration tests hang for up to a minute as each test calls `Connect()` (if the database is not running)
* start the database using `docker-compose up db`
* run `make test-integration`
* Tests should pass
* You shouldn't see any server logs
* now kill the database container
* now run `make test-integration` again
* tests should not pass
Ping @psturc
=> fix: clean up test commands in makefile

pkg/mobile/types.go, pkg/mobile/types_test.go
With this PR, application now accepts the following security related payload.
```
{
"clientId": "9796fb69-a566-43fb-b932-03951d82437f",
"timestamp": 1519989859342,
"data": {
"security": [
{
"id": "org.aerogear.mobile.security.checks.DeveloperModeCheck",
"name": "Developer Mode Check",
"passed": true
},
{
"id": "org.aerogear.mobile.security.checks.EmulatorCheck",
"name": "Emulator Check",
"passed": false
},
{
"id": "org.aerogear.mobile.security.checks.DebuggerCheck",
"name": "Debugger Check",
"passed": false
},
{
"id": "org.aerogear.mobile.security.checks.RootedCheck",
"name": "Rooted Check",
"passed": false
},
{
"id": "org.aerogear.mobile.security.checks.ScreenLockCheck",
"name": "Screen Lock Check",
"passed": false
}
]
}
}
```
This goes hand in hand with the changes being introduced in …
=> breaking: rename Type field in SecurityMetric to Id

pkg/web/metricsHandler.go, pkg/web/metricsHandler_test.go
Returning 200 status with empty content breaks IOS and Android parsers who will expect JSON file. However when returning 204 status code parsers will work fine.
204 is expected status code when no content is returned. 
Changes tested on IOS and Android. No adjustments needed in SDK's.
=> Change metrics endpoint status code to NO_CONTENT

pkg/dao/db.go
A couple changes to the table initialization to improve querying support.
Benchmarks have suggested this doesn't decrease insertion performance a noticeable level.
Add PK and the UNLOGGED flag to the mobileappmetrics table
=> Add PK and the UNLOGGED flag to mobileappmetrics table

openshift-template.yml
Added OpenShift template
As we're using app-metrics template for integration tests in 2 repos,
(https://github.com/aerogear/aerogear-android-sdk/pull/127, https://github.com/aerogear/aerogear-ios-sdk/pull/54) it would be reasonable to keep and maintain the template in one place.
The template was created according to the [provisioning role](https://github.com/aerogearcatalog/metrics-apb/blob/master/roles/provision-metrics-apb/tasks/provision-app-metrics.yml) in metrics-apb.
You can verify it with running `oc new-app -f openshift-template.yml` in empty project of your OpenShift cluster.
Then run the curl command to create a record in db:
```
curl -X POST \                                                                                                                          ⬡ 6.11.3 …
```
=> feat: OpenShift template

cmd/metrics-api/metrics-api.go, internal/setup/setup.go, pkg/config/config.go, pkg/config/config_test.go, pkg/dao/dao.go, pkg/mobile/types.go, pkg/mobile/types_test.go, pkg/test/fixtures.go, pkg/test/metrics-api_test.go, pkg/web/metricsHandler_test.go
Add integration tests that utilize the whole HTTP setup.
JIRA: https://issues.jboss.org/browse/AEROGEAR-2251
Moved most of the initialization code to `internal/setup`, following guidelines in https://github.com/golang-standards/project-layout#internal
Moved some of the fixtures to the new `test.fixtures` package for sharing. Would love to iterate on the way this is done.
=> feat: HTTP integration tests

openshift-template.yml
Use `master` version of docker image in template
Integration tests implemented in ios-sdk and android-sdk repos are using this template for testing and they should use the newest version of the app metrics docker image, which is [master](https://hub.docker.com/r/aerogear/aerogear-app-metrics/tags/)
`latest` image is ~1 month old
=> fix: use master version of the image in template

cmd/metrics-api/metrics-api.go, pkg/web/metricsHandler.go, pkg/web/router.go
Allow to use metrics api with CORS that is by default enabled for the web.
Since multiple users with multiple different IP ranges needs to call this server using Cors with any other value that * makes no sense here. 
Run server with docker compose and try it out with cordova example app.
=> Enable cors requests

Dockerfile.rhel7
This label will get added automatically by the build system.
=> 🎨 Remove 'vendor' label from Dockerfile.rhel7
